name: Build
on:
  push:
    branches:
      - "main"

jobs:
  go-build-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24.3'

    - name: Build
      run: make build

    - name: Test
      run: make test

  build-docker:
    runs-on: ubuntu-latest
    needs: go-build-test

    strategy:
      matrix:
        image: [ "woodpecker-ai", "woodpecker-executor" ]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker Meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/${{ github.repository }}/${{matrix.image}}
          tags: |
            type=ref,event=branch
            type=sha,prefix={{branch}}-
            type=sha,format=long,prefix={{branch}}-

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        uses: docker/build-push-action@v5
        with:
          context: .
          file: "build/Dockerfile.${{matrix.image}}"
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
