name: Pull Request
on:
  pull_request:

jobs:
  go-build-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24.3'

    - name: Build
      run: make build

    - name: Test
      run: make test
